name: position_data
description: Position data shown

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Provides equality between objects of same type.
  equatable: ^1.2.5

  # Charts.
  charts_flutter: ^0.9.0

  # Google Maps.
  google_maps_flutter: ^1.1.1

  # Bloc.
  flutter_bloc: ^6.1.1

  # Freezed metadata.
  freezed_annotation: ^0.12.0

  # Many core convenience tools.
  get: ^3.24.0

  # Make http requests.
  http: ^0.12.2

  # Mock library.
  mockito: ^4.1.3

  # retry asynchronous functions
  retry: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: ^1.11.0
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  lint: ^1.5.1
  test: ^1.15.7

flutter:
  uses-material-design: true
